name: Greetings

on: [pull_request, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: 'Thanks for collaborating on this project. Please read the collaborating and code of conduct documents before doing any code changes.'
        pr-message: 'Thanks for collaborating on this project. Please request a review from one or two of the other team members.'
